"""add exercises JSON column to lessons

Revision ID: 1477f63939e3
Revises: 35a332204be4
Create Date: 2026-07-04 17:47:36.086021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1477f63939e3'
down_revision: Union[str, Sequence[str], None] = '35a332204be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('exercises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'exercises')
    # ### end Alembic commands ###
