/**
 * Learning page copy
 */

export const learning = {
  curriculum: {
    continueLearning: "Continue Learning",
    currentStreak: "Day Streak",
    nextLesson: "Next up",
    completed: "Completed",
    complete: "Complete",
    minutes: "{n} min",
    lessons: "{n} lessons",
    level: "{level} · {name}",
    startFirst: "Start your first lesson to track your progress",
  },
  lesson: {
    start: "Start Lesson",
    continue: "Continue",
    next: "Next",
    previous: "Previous",
    complete: "Mark Complete",
    objectives: "Learning Objectives",
    vocabulary: "Vocabulary",
    grammar: "Grammar Notes",
    summary: "Lesson Complete!",
    summaryMessage: "Great work! Here's what you learned.",
  },
  quiz: {
    title: "Quiz",
    start: "Start Quiz",
    submit: "Submit Answers",
    next: "Next Question",
    results: "Your Results",
    score: "{correct}/{total} correct",
    percentScore: "{pct}%",
    review: "Review Answers",
    retry: "Try Again",
    loading: "Loading questions...",
    noQuestions: "No questions available for this topic.",
  },
  review: {
    title: "Today's Review",
    cardsReady: "{count} card{s} ready",
    allCaughtUp: "All caught up!",
    estimatedMinutes: "~{min} min · spaced repetition keeps words in your long-term memory",
    allCaughtUpDesc: "Nothing due right now — great work staying on top of your reviews.",
    reviewStreak: "Review Streak",
    due: "{count} card{s} due",
    mastered: "{count} mastered",
    rate: "How well did you know this?",
    hard: "Hard",
    good: "Good",
    easy: "Easy",
  },
  grammar: {
    title: "Grammar Library",
    searchPlaceholder: "Search grammar topics...",
    noResults: "No grammar topics found for your search.",
    level: "All",
    loading: "Loading grammar topics...",
    example: "Example",
    relatedLessons: "Related Lessons",
  },
  settings: {
    title: "Settings",
    subtitle: "Manage your profile, learning preferences, and account",
    profile: "Profile",
    subscription: "Subscription",
    learning: "Learning",
    appearance: "Appearance",
    audio: "Audio",
    notifications: "Notifications",
    accessibility: "Accessibility",
    privacy: "Privacy & Data",
    account: "Account",
    save: "Save Changes",
    saved: "Changes saved successfully.",
    error: "Failed to save changes. Please try again.",
  },
} as const;
